// Generated by Flutter Assets

// ignore_for_file: unused_field, camel_case_types, non_constant_identifier_names, library_private_types_in_public_api

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
        
class Assets extends StatelessWidget {
  final AssetsData assets;
  final Widget child;

  const Assets({
    super.key,
    required this.assets,
    required this.child,
  });

  static AssetsData of(BuildContext context) {
    final widget = context.dependOnInheritedWidgetOfExactType<_InheritedAssets>();
    return widget?.assets ?? AssetsData.light();
  }

  @override
  Widget build(BuildContext context) {
    return _InheritedAssets(
      assets: assets,
      child: child,
    );
  }
}

class _InheritedAssets extends InheritedWidget {
  final AssetsData assets;

  const _InheritedAssets({
    required this.assets,
    required super.child,
  });

  @override
  bool updateShouldNotify(covariant _InheritedAssets oldWidget) => assets != oldWidget.assets;
}

class AssetsData {
  static AssetsData? _light;
  static AssetsData? _dark;

  factory AssetsData.light() => _light ??= AssetsData._(brightness: Brightness.light);
  factory AssetsData.dark() => _dark ??= AssetsData._(brightness: Brightness.dark);
  factory AssetsData.brightness(Brightness brightness) => brightness == Brightness.light ? AssetsData.light() : AssetsData.dark();

  final Brightness _brightness;

  AssetsData._({
    required Brightness brightness,
  })  : _brightness = brightness,
        fonts = _assets_fonts_dart._(brightness: brightness),
        icons = _assets_icons_dart._(brightness: brightness),
        images = _assets_images_dart._(brightness: brightness);

  final _assets_fonts_dart fonts;
  final _assets_icons_dart icons;
  final _assets_images_dart images;
}

class _assets_fonts_dart {
  final Brightness _brightness;

  _assets_fonts_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final InstrumentSans_Bold_ttf = 'assets/fonts/InstrumentSans-Bold.ttf';
  final InstrumentSans_Regular_ttf = 'assets/fonts/InstrumentSans-Regular.ttf';
  final InstrumentSans_SemiBold_ttf = 'assets/fonts/InstrumentSans-SemiBold.ttf';
}

class _assets_icons_dart {
  final Brightness _brightness;

  _assets_icons_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final bell_png = 'assets/icons/bell.png';
  final burger_menu_png = 'assets/icons/burger_menu.png';
  final cyan_plus_png = 'assets/icons/cyan_plus.png';
  final email_png = 'assets/icons/email.png';
  final heart_png = 'assets/icons/heart.png';
  final home_png = 'assets/icons/home.png';
  final password_png = 'assets/icons/password.png';
  final person_png = 'assets/icons/person.png';
  final person_filled_png = 'assets/icons/person_filled.png';
  final scanner_png = 'assets/icons/scanner.png';
  final search_png = 'assets/icons/search.png';
  final shopping_cart_png = 'assets/icons/shopping_cart.png';
}

class _assets_images_dart {
  final Brightness _brightness;

  _assets_images_dart._({
    required Brightness brightness,
  })  : _brightness = brightness;

  final login_png = 'assets/images/login.png';
  final otp_png = 'assets/images/otp.png';
  final shopping_png = 'assets/images/shopping.png';
  final splash_logo_png = 'assets/images/splash_logo.png';
}
